Weapons = {
    ['WEAPON_PISTOL50'] = {
        ['pistol502'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = false, ['COMPONENT_PISTOL50_CLIP_02'] = false}, name = 'Desert Eagle' },
        ['pistol502-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = false, ['COMPONENT_PISTOL50_CLIP_02'] = true}, name = 'Desert Eagle' },
        ['pistol502-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = true, ['COMPONENT_PISTOL50_CLIP_02'] = false}, name = 'Desert Eagle'},
        ['pistol502-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = true, ['COMPONENT_PISTOL50_CLIP_02'] = true}, name = 'Desert Eagle'},
        ['pistol502-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = false, ['COMPONENT_PISTOL50_CLIP_02'] = false}, name = 'Desert Eagle'},
        ['pistol502-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = false, ['COMPONENT_PISTOL50_CLIP_02'] = true}, name = 'Desert Eagle'},
        ['pistol502-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = true, ['COMPONENT_PISTOL50_CLIP_02'] = false}, name = 'Desert Eagle'},
        ['pistol502-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = true, ['COMPONENT_PISTOL50_CLIP_02'] = true}, name = 'Desert Eagle'},
    },
    ['WEAPON_VINTAGEPISTOL'] = {
        ['vintagepistol2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false}, name ='FN Model 1910'},
        ['vintagepistol2-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true}, name ='FN Model 1910'},
    },
    ['WEAPON_SNSPISTOL'] = {
        ['snspistol2'] = {COMPONENTS = nil, name = 'H&K P7'},
    },
    ['WEAPON_MACHINEPISTOL'] = {
        ['machinepistol2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false,}, name = 'Machine Pistol'},
        ['machinepistol2-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true}, name = 'Machine Pistol'},
    },
    ['WEAPON_PISTOL_MK2'] = {
        ['pistol_mk2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_RAIL'] = false, ['COMPONENT_AT_PI_FLSH_02'] = false}, name = 'Sig Sauer P226'},
        ['pistol_mk2-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_RAIL'] = false, ['COMPONENT_AT_PI_FLSH_02'] = true}, name = 'Sig Sauer P226'},
        ['pistol_mk2-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_RAIL'] = true, ['COMPONENT_AT_PI_FLSH_02'] = false}, name = 'Sig Sauer P226'},
        ['pistol_mk2-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_RAIL'] = true, ['COMPONENT_AT_PI_FLSH_02'] = true}, name = 'Sig Sauer P226'},
        ['pistol_mk2-5'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_RAIL'] = false, ['COMPONENT_AT_PI_FLSH_02'] = false}, name = 'Sig Sauer P226'},
        ['pistol_mk2-6'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_RAIL'] = false, ['COMPONENT_AT_PI_FLSH_02'] = true}, name = 'Sig Sauer P226'},
        ['pistol_mk2-7'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_RAIL'] = true, ['COMPONENT_AT_PI_FLSH_02'] = false}, name = 'Sig Sauer P226'},
        ['pistol_mk2-8'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_RAIL'] = true, ['COMPONENT_AT_PI_FLSH_02'] = true}, name = 'Sig Sauer P226'},
    },
    ['WEAPON_HEAVYPISTOL'] = {
        ['heavypistol'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'EWB 1911'},
        ['heavypistol-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'EWB 1911'},
        ['heavypistol-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'EWB 1911'},
        ['heavypistol-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'EWB 1911'},
    },
    ['WEAPON_MINISMG'] = {
        ['minismg'] = {COMPONENTS = nil, name = 'Skorpion Vz. 61'},
    },
    ['WEAPON_SMG'] = {
        ['smg2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['smg2-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['smg2-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = false  }, name = 'SMG'},
        ['smg2-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['smg2-5'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['smg2-6'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['smg2-7'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['smg2-8'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},

        ['police_smg2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['police_smg2-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['police_smg2-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = false  }, name = 'SMG'},
        ['police_smg2-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['police_smg2-5'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['police_smg2-6'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
        ['police_smg2-7'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = false}, name = 'SMG'},
        ['police_smg2-8'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_SCOPE_MACRO_02'] = true}, name = 'SMG'},
    },
    ['WEAPON_COMPACTRIFLE'] = {
        ['compactrifle2'] = {COMPONENTS = {['COMPONENT_COMPACTRIFLE_CLIP_02'] = false}, name = 'Compact AK-47'},
        ['compactrifle2-2'] = {COMPONENTS = {['COMPONENT_COMPACTRIFLE_CLIP_02'] = true}, name = 'Compact AK-47'},
    },
    ['WEAPON_DBSHOTGUN'] = {
        ['dbshotgun2'] = {COMPONENTS = nil, name = 'Double Barrel Shotgun'},
    },
    ['WEAPON_SAWNOFFSHOTGUN'] = {
        ['sawnoffshotgun2'] = {COMPONENTS = nil, name = 'Sawed-off Shotgun'},
    },
    ['WEAPON_ASSAULTRIFLE'] = {
        ['assaultrifle2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-9'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-10'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-11'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-12'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-13'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-14'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-15'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-16'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-17'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-18'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-19'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-20'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-21'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-22'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-23'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-24'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-25'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-26'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-27'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-28'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-29'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-30'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
        ['assaultrifle2-31'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = false}, name = 'AK-47'},
        ['assaultrifle2-32'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_ASSAULTRIFLE_CLIP_02'] = true}, name = 'AK-47'},
    },
    ['WEAPON_MICROSMG'] = {
        ['microsmg2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Micro SMG'},
        ['microsmg2-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Micro SMG'},
        ['microsmg2-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Micro SMG'},
        ['microsmg2-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Micro SMG'},
        ['microsmg2-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Micro SMG'},
        ['microsmg2-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Micro SMG'},
        ['microsmg2-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Micro SMG'},
        ['microsmg2-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Micro SMG'},
    },
    ['WEAPON_ASSAULTSMG'] = {
        ['assaultsmg'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['assaultsmg-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['assaultsmg-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['assaultsmg-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['assaultsmg-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['assaultsmg-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['assaultsmg-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['assaultsmg-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},

        ['police_assaultsmg'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['police_assaultsmg-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['police_assaultsmg-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['police_assaultsmg-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['police_assaultsmg-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['police_assaultsmg-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
        ['police_assaultsmg-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'P90'},
        ['police_assaultsmg-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MACRO'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'P90'},
    },
    ['WEAPON_CARBINERIFLE'] = {
        ['carbinerifle'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-9'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-10'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-11'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-12'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-13'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-14'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-15'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-16'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-17'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-18'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-19'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-20'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-21'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-22'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-23'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-24'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-25'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-26'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-27'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-28'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-29'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-30'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
        ['carbinerifle-31'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = false}, name = 'SIG MCX'},
        ['carbinerifle-32'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_FLSH'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_CARBINERIFLE_CLIP_02'] = true}, name = 'SIG MCX'},
    },
    ['WEAPON_PISTOL'] = {
        ['zipper3000'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Walter P99q'},
        ['zipper3000-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = false, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Walter P99q'},
        ['zipper3000-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Walter P99q'},
        ['zipper3000-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP_02'] = true, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Walter P99q'},
    },
    ['WEAPON_COMBATPISTOL'] = {
        ['combatpistol'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Glock 17'},
        ['combatpistol-2'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = false, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Glock 17'},
        ['combatpistol-3'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_PI_FLSH'] = false}, name = 'Glock 17'},
        ['combatpistol-4'] = {COMPONENTS = {['COMPONENT_AT_PI_SUPP'] = true, ['COMPONENT_AT_PI_FLSH'] = true}, name = 'Glock 17'},
    },
    ['WEAPON_ADVANCEDRIFLE'] = {
        ['advancedrifleklu'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_SMALL'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'M4A1'},
        ['advancedrifleklu-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_SMALL'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'M4A1'},
        ['advancedrifleklu-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_SMALL'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'M4A1'},
        ['advancedrifleklu-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_SMALL'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'M4A1'},
        ['advancedrifleklu-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_SMALL'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'M4A1'},
        ['advancedrifleklu-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_SMALL'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'M4A1'},
        ['advancedrifleklu-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_SMALL'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'M4A1'},
        ['advancedrifleklu-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_SMALL'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'M4A1'},

    },
    ['WEAPON_MG'] = {
        ['mg'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_SMALL_02'] = false }, name = 'MG'},
        ['mg-2'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_SMALL_02'] = true }, name = 'MG'},
    },
    ['WEAPON_COMBATMG'] = {
        ['combatmg'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false }, name = 'M249E1'},
        ['combatmg-2'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true }, name = 'M249E1'},
        ['combatmg-3'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false }, name = 'M249E1'},
        ['combatmg-4'] = {COMPONENTS = {['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true }, name = 'M249E1'},
    },
    ['WEAPON_PUMPSHOTGUN'] = {
        ['pumpshotgun'] = {COMPONENTS = {['COMPONENT_AT_SR_SUPP'] = false }, name = 'Shotgun'},
        ['pumpshotgun-2'] = {COMPONENTS = {['COMPONENT_AT_SR_SUPP'] = true }, name = 'Shotgun'},
    },
    ['WEAPON_SNIPERRIFLE'] = {
        ['sniperriflesierra'] = {COMPONENTS = nil, name ='DSI Sniper'}
    },
    ['WEAPON_SPECIALCARBINE'] = {
        ['specialcarbine'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = false, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-9'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-10'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-11'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-12'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = false, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-13'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-14'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['specialcarbine-15'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['specialcarbine-16'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP_02'] = true, ['COMPONENT_AT_SCOPE_MEDIUM'] = true, ['COMPONENT_AT_AR_AFGRIP'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
    },
    ['WEAPON_CARBINERIFLE_MK2'] = {
        ['carbinerifle_mk2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-3'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-4'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-5'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-6'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-7'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-8'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-9'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-10'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-11'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-12'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = false, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-13'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-14'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = false, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
        ['carbinerifle_mk2-15'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = false}, name = 'HK 416'},
        ['carbinerifle_mk2-16'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true, ['COMPONENT_AT_SCOPE_MACRO_MK2'] = true, ['COMPONENT_AT_AR_AFGRIP_02'] = true, ['COMPONENT_AT_AR_FLSH'] = true}, name = 'HK 416'},
    },
    ['WEAPON_KNIFE'] = {
        ['knife2'] = {COMPONENTS = nil, name = 'Mes'},
    },
    ['WEAPON_NIGHTSTICK'] = {
        ['nightstick'] = {COMPONENTS = nil, name = 'Wapenstok'},
    },
    ['WEAPON_HAMMER'] = {
        ['hammer'] = {COMPONENTS = nil, name = 'Hammer'},
    },
    ['WEAPON_BAT'] = {
        ['bat2'] = {COMPONENTS = nil, name = 'Knuppel'},
    },
    ['WEAPON_GOLFCLUB'] = {
        ['golfclub'] = {COMPONENTS = nil, name = 'Golfclub'},
    },
    ['WEAPON_CROWBAR'] = {
        ['crowbar'] = {COMPONENTS = nil, name = 'Crowbar'},
    },
    ['WEAPON_STUNGUN'] = {
        ['stungun'] = {COMPONENTS = nil, name = 'Stroomstootwapen'},
    },
    ['WEAPON_FIREEXTINGUISHER'] = {
        ['fireextinguisher'] = {COMPONENTS = nil, name = 'Brandblusser'},
    },
    ['WEAPON_PETROLCAN'] = {
        ['petrolcan'] = {COMPONENTS = nil, name = 'Jerrycan'},
    },
    ['WEAPON_GUSENBERG'] = {
        ['gusenberg'] = {COMPONENTS = {['COMPONENT_GUSENBERG_CLIP_02'] = false}, name = 'Gusenberg'},
        ['gusenberg-2'] = {COMPONENTS = {['COMPONENT_GUSENBERG_CLIP_02'] = true}, name = 'Gusenberg'},
    },
    ['WEAPON_BULLPUPRIFLE'] = {
        ['landbullpuprifle'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false}, name ='L82A2'},
        ['landbullpuprifle-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true}, name ='L82A2'},
    },
    ['WEAPON_MUSKET'] = {
        ['musket'] = {COMPONENTS = nil, name = 'Musket'},
    },
    ['WEAPON_MARKSMANRIFLE'] = {
        ['marksmanrifle2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = false}, name ='Marksman Rifle'},
        ['marksmanrifle2-2'] = {COMPONENTS = {['COMPONENT_AT_AR_SUPP'] = true}, name ='Marksman Rifle'},
    },
    ['WEAPON_SNOWBALL'] = {
        ['snowball'] = {COMPONENTS = nil, name = 'Sneeuwbal'},
    },
    ['WEAPON_KNUCKLE'] = {
        ['knuckle2'] = {COMPONENTS = nil, name = 'Boksbeugel'},
    },
    ['WEAPON_MACHETE'] = {
        ['machete2'] = {COMPONENTS = nil, name = 'Machete'},
    },
    ['WEAPON_SWITCHBLADE'] = {
        ['switchblade2'] = {COMPONENTS = nil, name = 'Switchblade'},
    },
    ['WEAPON_REVOLVER'] = {
        ['revolver'] = {COMPONENTS = nil, name = 'Heavy revolver' },
    },
    ['WEAPON_WRENCH'] = {
        ['wrench'] = {COMPONENTS = nil, name = 'Loodgieter sleutel'},
    },
    ['WEAPON_FLASHLIGHT'] = {
        ['flashlight'] = {COMPONENTS = nil, name = 'Zaklamp'},
    },
    ['GADGET_PARACHUTE'] = {
        ['parachute'] = {COMPONENTS = nil, name = 'Parachute'},
    },
    ['WEAPON_DOUBLEACTION'] = {
        ['doubleaction'] = {COMPONENTS = nil, name = 'Revolver'},
    },
}



